import Header from './components/Header'; // Ensure the path is correct
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "../styles/globals.css"; // Correct the path to the global CSS file

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Header />
        <main>{children}</main>
      </body>
    </html>
  );
}
